from test_utils import *
import pytest

@pytest.mark.parametrize(
	"input_,expected",
	[
		("a", False),
		("aa", False),
		("a*", True),
		("a+a", False),
		("a(a+aa+aaa)", False),
		("e+a", False),
		("e+aa*", True),

		("e", False),
		("aa*", False),
		("a*", True),
		("(a*)*", True),
		("(e+a)*", True),
		("a+aa*", False),
		("aa+aaa*", False),
		("a(a*)", False),
		("(a+a*)", True),
		("(a+e)*", True),
		("(a+aa+aaa)*", True),
		("(a+aaa)", False),
		("(aa+aaa)", False),
		("(a*+aa)", True),

		("(e+a*)", True),
		("(e+a+aa)*", True),
		("(a*+e)*", True),
		("(a+a*+e)*", True),
		("(a*+aa+e)", True),
		("(a*a*)", True),
		("(e+(a*))*", True),
		("((a+e)*)*", True),
		("(e+a+a*)", True),
		("(e+a+aa+aaa+aaaa)*", True),
		("(e+a*)*", True),
		("(a*+e+aa*)*", True),
		("((a+aa+e)*)*", True),
		("(a*+e+a+aa+aaa)*", True),

		("(e+(a*a*)*)", True),
		("((e+a)+a*)*", True),
		("(a*+e+aaa*)*", True),
		("((a+e*)*)*", True),
		("((a*)+e+aa*)*", True),
		("((e+a)+aa*)*", True),
		("(a*+(e+aa)*)*", True),
		("(a*+e*(a*)*)*", True),
		("(e+(a*+aa)*)*", True),
		("((a+aa+aaa+e)*)*", True),
		("(e+a*+a*a*)*", True),
		("((a+e+aa+aaa)*)*", True),
		("(a*+(e+a)*)*", True),
		("(e+((a*)*))", True),

		("aa*", False),
		("aaa*", False),
		("aaaa*", False),
		("a+a", False),
		("a+aa", False),
		("aa+a", False),
		("aa+aaa", False),
		("aaa+aa", False),
		("a(a+a)", False),
		("a(aa+aaa)", False),
		("aa(a+a)", False),
		("aa(aa+aaa)", False),
		("a(a+aa)", False),
		("a(aa+a)", False),
		("aa(a+aa)", False),
		("aa(aa+a)", False),
		("a+a+a", False),
		("aa+aa+aa", False),
		("aaa+aaa+aaa", False),
		("a+(aa+aaa)", False),
		("aa+(a+aaa)", False),
		("aaa+(a+aa)", False),
		("a+aa*+aa", False),
		("aa*+a+aa", False),
		("aa+aa*", False),
		("aaa+aa*", False),
		("a(a+a+aa)", False),
		("aa(a+aa+aaa)", False),
		("aaa(a+aa+aaa)", False),
		("a(a+aa)*", False),
		("aa(a+aa)*", False),
		("a+aa*", False),
		("aa+aaa*", False),
		("a+aaa*", False),
		("aa+aaaa*", False),
		("a(a+aa)*a", False),
		("aa(a+aa)*a", False),
		("a+aa+a", False),
		("aa+aa+aaa", False),
		("aaa+aa+aa", False),
		("a(a+aa+aaa)+a", False),
		("aa(a+aa+aaa)+a", False),
		("a+a+aa", False),
		("aa+a+aa", False),
		("a+aa+a", False),
		("aa+aaa+a", False),
		("aaa+a+aa", False),
		("a(a+aa)+aa", False),
		("aa(a+aa)+aaa", False),


		("a(aa)*+(aa)*", True),
		("aa(aaa)*+a(aaa)*+(aaa)*", True),
		("aa(aaa)*+(aaa)*", False),
		("(a+aaa)*+aa", True),
		("(a+aaa)*(aa)*", True),
		("(a+aaa)*+aa+(aa)*", True),
		("(a+aaa)*+aa*", True),
		("a + a + a +       aaa + a    a a a ", False),
		("aaaaa                             a+a\n+a*", True),



		("0", False),
		("0aaa", False),
		("0a*", False),
		("0*", False),

		("a0a", False),
		("a*0", False),
		("a+a+0", False),
		("a(0+a+aa+aaa)", False),
		("0 + e+a", False),
		("0+e+aa*", True),

		("0e", False),
		("e0", False),
		("0e0", False),
		("a* + 0", True),
		("(a* + 0)*", True),
		("(0 + e+a)*", True),
		("0 + a+aa*", False),
		("a0a+aaa*", False),
		("a        0                           a +aaa                                 *", False),


		("0", False),
		("0+0", False),
		("0+e", False),
		("e+0", False),
		("0*", False),
		("(0)*", False),
		("0a", False),
		("a0", False),
		("0+a", False),
		("a+0", False),
		("0+a*", True),
		("a*+0", True),
		("(0+a)*", True),
		("(0a)*", False),
		("(a0)*", False),
		("0e", False),
		("e0", False),
		("0+aa*", False),
		("(0+aa*)*", True),
		("0+0*", False),
		("(0+e)*", False),
		("0(a+e)*", False),
		("(a+e)*0", False),
	]
)
def test_checkreg(input_, expected):
	result = checkreg(input_)
	assert expected == result

